data <- read.csv("data/synthetic_api_interface_cases.csv", stringsAsFactors = FALSE)
data$interface_quality <- 100 * (0.12*data$contract_clarity + 0.12*data$schema_validation + 0.10*data$error_behavior + 0.10*data$versioning_strategy + 0.10*data$documentation_quality + 0.10*data$testability + 0.10*data$coupling_control + 0.08*data$observability + 0.10*data$security_boundaries + 0.08*data$governance_readiness)
data$interface_risk <- 100 * rowMeans(1 - data[, c("contract_clarity","schema_validation","error_behavior","versioning_strategy","documentation_quality","testability","coupling_control","security_boundaries")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_api_interface_summary.csv", row.names=FALSE)
png("outputs/figures/r_interface_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$interface_quality, data$interface_risk); colnames(m) <- data$case_name; rownames(m) <- c("Interface quality", "Interface risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Interface Quality vs. Interface Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
