args <- commandArgs(trailingOnly = TRUE)
formalization <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
machine_abstraction <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.98)
symbolic_representation <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.96)
universality <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.86)
decidability <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.90)
limit_awareness <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.92)
reasoning_relevance <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.96)
ai_relevance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.82)
governance_caution <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.86)
modern_resonance <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.98)

score <- mean(c(formalization, machine_abstraction, symbolic_representation, universality, decidability, limit_awareness, reasoning_relevance, ai_relevance, governance_caution, modern_resonance))
cat(sprintf("reasoning_score=%.6f\n", score))
