args <- commandArgs(trailingOnly = TRUE)
compiler_centrality <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
human_readability <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.96)
portability <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.92)
documentation <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.90)
standards <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.88)
debugging <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.86)
business_relevance <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.88)
institutional_scale <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.92)
abstraction <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.98)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.90)

score <- mean(c(compiler_centrality, human_readability, portability, documentation, standards, debugging, business_relevance, institutional_scale, abstraction, governance_caution))
cat(sprintf("humanization_score=%.6f\n", score))
