args <- commandArgs(trailingOnly = TRUE)
required_records <- ifelse(length(args) >= 1, as.numeric(args[1]), 12)
available_records <- ifelse(length(args) >= 2, as.numeric(args[2]), 9)
documentation <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.72)
provenance <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.68)
reviewability <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.64)
contestability <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.58)
remediation <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.52)
governance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.66)
stakes <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.90)
audit_completeness <- ifelse(required_records == 0, 0, available_records / required_records)
accountability_capacity <- mean(c(documentation, provenance, reviewability, contestability, remediation, governance))
reconstruction_risk <- stakes * (1 - audit_completeness)
cat(sprintf("audit_completeness_score=%.6f\n", audit_completeness))
cat(sprintf("accountability_capacity_score=%.6f\n", accountability_capacity))
cat(sprintf("reconstruction_risk_score=%.6f\n", reconstruction_risk))
