data <- read.csv("data/synthetic_parallelism_scale_cases.csv", stringsAsFactors = FALSE)
data$scale_claim_quality <- 100 * (0.10*data$decomposability + 0.09*data$partitioning_clarity + 0.10*data$communication_awareness + 0.08*data$synchronization_control + 0.09*data$load_balance_evidence + 0.08*data$data_locality_awareness + 0.10*data$fault_tolerance + 0.08*data$consistency_clarity + 0.10*data$benchmark_support + 0.07*data$cost_awareness + 0.06*data$governance_readiness + 0.05*data$communication_clarity)
data$scale_claim_risk <- 100 * rowMeans(1 - data[, c("decomposability","partitioning_clarity","communication_awareness","synchronization_control","load_balance_evidence","data_locality_awareness","fault_tolerance","consistency_clarity","benchmark_support","cost_awareness","governance_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_parallelism_scale_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_scale_claim_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$scale_claim_quality, data$scale_claim_risk); colnames(m) <- data$case_name; rownames(m) <- c("Scale claim quality", "Scale claim risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Parallel and Distributed Scale Claim Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
