args <- commandArgs(trailingOnly = TRUE)
algorithm_analysis <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
exposition <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.98)
mathematical_rigor <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.98)
historical_depth <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.94)
implementation_relevance <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.94)
typography_relevance <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.88)
literate_programming <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.90)
pedagogy <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.98)
maintainability <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.92)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.90)

score <- mean(c(algorithm_analysis, exposition, mathematical_rigor, historical_depth, implementation_relevance, typography_relevance, literate_programming, pedagogy, maintainability, governance_caution))
cat(sprintf("art_score=%.6f\n", score))
