data <- read.csv("data/synthetic_streaming_cases.csv", stringsAsFactors = FALSE)
data$streaming_claim_quality <- 100 * (0.09*data$bounded_memory_clarity + 0.09*data$approximation_transparency + 0.08*data$event_time_handling + 0.08*data$late_data_policy + 0.08*data$window_design + 0.07*data$sampling_quality + 0.08*data$sketch_suitability + 0.09*data$throughput_awareness + 0.08*data$alert_governance + 0.07*data$retention_policy + 0.07*data$privacy_review + 0.06*data$fallback_readiness + 0.06*data$communication_clarity)
data$streaming_claim_risk <- 100 * rowMeans(1 - data[, c("bounded_memory_clarity","approximation_transparency","event_time_handling","late_data_policy","window_design","sampling_quality","sketch_suitability","throughput_awareness","alert_governance","retention_policy","privacy_review","fallback_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_streaming_algorithm_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_streaming_claim_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$streaming_claim_quality, data$streaming_claim_risk); colnames(m) <- data$case_name; rownames(m) <- c("Streaming claim quality", "Streaming claim risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Streaming Claim Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
