data <- read.csv("data/synthetic_divide_conquer_cases.csv", stringsAsFactors = FALSE)
data$divide_conquer_quality <- 100 * (0.12*data$decomposition_clarity + 0.10*data$base_case_clarity + 0.10*data$subproblem_validity + 0.12*data$progress_toward_termination + 0.12*data$combination_correctness + 0.10*data$recurrence_awareness + 0.10*data$edge_case_coverage + 0.08*data$boundary_handling + 0.08*data$traceability + 0.08*data$governance_readiness)
data$divide_conquer_risk <- 100 * rowMeans(1 - data[, c("decomposition_clarity","base_case_clarity","subproblem_validity","progress_toward_termination","combination_correctness","recurrence_awareness","edge_case_coverage","boundary_handling","traceability","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_divide_conquer_summary.csv", row.names=FALSE)
png("outputs/figures/r_divide_conquer_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$divide_conquer_quality, data$divide_conquer_risk); colnames(m) <- data$case_name; rownames(m) <- c("Divide-and-conquer quality", "Divide-and-conquer risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Divide-and-Conquer Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
