args <- commandArgs(trailingOnly = TRUE)
procedural_explicitness <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
representation <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.94)
proof_correctness <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.92)
portability <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.98)
mechanization <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.54)
formalization <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.84)
programmability <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.42)
institutional_adoption <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.94)
governance_relevance <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.72)
modern_resonance <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.98)

score <- mean(c(procedural_explicitness, representation, proof_correctness, portability, mechanization, formalization, programmability, institutional_adoption, governance_relevance, modern_resonance))
cat(sprintf("history_score=%.6f\n", score))
