search_strategy(breadth_first).
search_strategy(depth_first).
search_strategy(uniform_cost).
search_strategy(best_first).
search_strategy(heuristic_search).
search_strategy(local_search).
requires_governance(state_specification).
requires_governance(transition_specification).
requires_governance(goal_definition).
requires_governance(constraint_record).
requires_governance(heuristic_documentation).
requires_governance(pruning_record).
requires_governance(coverage_report).
requires_governance(stopping_condition).
risk(missing_states).
risk(invalid_transitions).
risk(hidden_constraints).
risk(biased_heuristic).
risk(premature_pruning).
risk(false_completeness).
