data <- read.csv("data/synthetic_p_np_hardness_cases.csv", stringsAsFactors = FALSE)
data$complexity_class_claim_quality <- 100 * (0.09*data$problem_form_clarity + 0.09*data$input_definition_clarity + 0.10*data$certificate_clarity + 0.10*data$verifier_clarity + 0.10*data$reduction_evidence + 0.12*data$class_claim_evidence + 0.10*data$exact_method_feasibility + 0.08*data$approximation_readiness + 0.08*data$benchmark_support + 0.07*data$governance_readiness + 0.07*data$communication_clarity)
data$complexity_class_claim_risk <- 100 * rowMeans(1 - data[, c("problem_form_clarity","input_definition_clarity","certificate_clarity","verifier_clarity","reduction_evidence","class_claim_evidence","exact_method_feasibility","approximation_readiness","benchmark_support","governance_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_p_np_hardness_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_p_np_claim_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$complexity_class_claim_quality, data$complexity_class_claim_risk); colnames(m) <- data$case_name; rownames(m) <- c("Claim quality", "Claim risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="P, NP, and Hardness Claim Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
