data <- read.csv("data/synthetic_evolutionary_search_cases.csv", stringsAsFactors = FALSE)
data$evolutionary_search_quality <- 100 * (0.12*data$representation_clarity + 0.12*data$fitness_alignment + 0.10*data$variation_design + 0.10*data$diversity_tracking + 0.10*data$parameter_documentation + 0.12*data$benchmark_evidence + 0.10*data$robustness_testing + 0.08*data$traceability + 0.08*data$safety_review + 0.08*data$governance_readiness)
data$evolutionary_search_risk <- 100 * rowMeans(1 - data[, c("representation_clarity","fitness_alignment","variation_design","diversity_tracking","parameter_documentation","benchmark_evidence","robustness_testing","traceability","safety_review","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_evolutionary_search_summary.csv", row.names=FALSE)
png("outputs/figures/r_evolutionary_search_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$evolutionary_search_quality, data$evolutionary_search_risk); colnames(m) <- data$case_name; rownames(m) <- c("Evolutionary search quality", "Evolutionary search risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Evolutionary Search Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
