data <- read.csv("data/synthetic_algorithm_design_cases.csv", stringsAsFactors = FALSE)
data$design_quality <- 100 * (0.12*data$problem_formulation + 0.10*data$input_output_clarity + 0.12*data$correctness_rationale + 0.10*data$termination_argument + 0.10*data$complexity_analysis + 0.10*data$data_structure_fit + 0.10*data$edge_case_coverage + 0.10*data$robustness + 0.08*data$interpretability + 0.08*data$governance_readiness)
data$design_risk <- 100 * rowMeans(1 - data[, c("problem_formulation","input_output_clarity","correctness_rationale","termination_argument","complexity_analysis","edge_case_coverage","robustness","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_algorithm_design_summary.csv", row.names=FALSE)
png("outputs/figures/r_algorithm_design_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$design_quality, data$design_risk); colnames(m) <- data$case_name; rownames(m) <- c("Design quality", "Design risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Algorithm Design Quality vs. Design Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
