data <- read.csv("data/synthetic_dynamic_programming_cases.csv", stringsAsFactors = FALSE)
data$dynamic_programming_quality <- 100 * (0.12*data$state_clarity + 0.12*data$recurrence_validity + 0.10*data$base_case_clarity + 0.10*data$overlapping_subproblem_evidence + 0.10*data$optimal_substructure_evidence + 0.10*data$transition_clarity + 0.10*data$storage_strategy_quality + 0.10*data$edge_case_coverage + 0.08*data$traceability + 0.08*data$governance_readiness)
data$dynamic_programming_risk <- 100 * rowMeans(1 - data[, c("state_clarity","recurrence_validity","base_case_clarity","overlapping_subproblem_evidence","optimal_substructure_evidence","transition_clarity","storage_strategy_quality","edge_case_coverage","traceability","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_dynamic_programming_summary.csv", row.names=FALSE)
png("outputs/figures/r_dynamic_programming_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$dynamic_programming_quality, data$dynamic_programming_risk); colnames(m) <- data$case_name; rownames(m) <- c("Dynamic programming quality", "Dynamic programming risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Dynamic Programming Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
