args <- commandArgs(trailingOnly = TRUE)
formalization <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
functional_abstraction <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.98)
symbolic_transformation <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.98)
substitution <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.96)
reduction <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.96)
computability <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.96)
undecidability <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.86)
type_influence <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.88)
programming_relevance <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.98)
ai_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.86)

score <- mean(c(formalization, functional_abstraction, symbolic_transformation, substitution, reduction, computability, undecidability, type_influence, programming_relevance, ai_caution))
cat(sprintf("formal_score=%.6f\n", score))
