data <- read.csv("data/synthetic_online_decision_cases.csv", stringsAsFactors = FALSE)
data$online_decision_quality <- 100 * (0.11*data$information_at_decision_clarity + 0.10*data$arrival_model_clarity + 0.10*data$commitment_awareness + 0.09*data$threshold_transparency + 0.10*data$prediction_error_handling + 0.10*data$competitive_or_regret_evidence + 0.10*data$queue_and_capacity_awareness + 0.09*data$fairness_under_arrival_review + 0.08*data$fallback_readiness + 0.07*data$governance_readiness + 0.06*data$communication_clarity)
data$online_decision_risk <- 100 * rowMeans(1 - data[, c("information_at_decision_clarity","arrival_model_clarity","commitment_awareness","threshold_transparency","prediction_error_handling","competitive_or_regret_evidence","queue_and_capacity_awareness","fairness_under_arrival_review","fallback_readiness","governance_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_online_decision_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_online_decision_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$online_decision_quality, data$online_decision_risk); colnames(m) <- data$case_name; rownames(m) <- c("Online decision quality", "Online decision risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Online Decision Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
