data <- read.csv("data/synthetic_runtime_context_cases.csv", stringsAsFactors = FALSE)
data$runtime_quality <- 100 * (0.10*data$runtime_documentation + 0.12*data$dependency_control + 0.10*data$configuration_validation + 0.10*data$resource_visibility + 0.08*data$portability_support + 0.12*data$reproducibility_support + 0.12*data$security_boundaries + 0.10*data$observability + 0.08*data$external_service_discipline + 0.08*data$governance_readiness)
data$runtime_risk <- 100 * rowMeans(1 - data[, c("runtime_documentation","dependency_control","configuration_validation","resource_visibility","reproducibility_support","security_boundaries","observability","external_service_discipline")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_runtime_context_summary.csv", row.names=FALSE)
png("outputs/figures/r_runtime_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$runtime_quality, data$runtime_risk); colnames(m) <- data$case_name; rownames(m) <- c("Runtime quality", "Runtime risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Runtime Quality vs. Runtime Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
