data <- read.csv("data/synthetic_search_sorting_cases.csv", stringsAsFactors = FALSE)
data$search_sorting_quality <- 100 * (0.12*data$search_space_clarity + 0.12*data$predicate_or_key_clarity + 0.10*data$ordering_rule_quality + 0.10*data$data_structure_fit + 0.10*data$complexity_awareness + 0.10*data$edge_case_coverage + 0.10*data$stability_or_tie_breaking + 0.08*data$traceability + 0.10*data$robustness + 0.08*data$governance_readiness)
data$search_sorting_risk <- 100 * rowMeans(1 - data[, c("search_space_clarity","predicate_or_key_clarity","ordering_rule_quality","data_structure_fit","complexity_awareness","edge_case_coverage","stability_or_tie_breaking","traceability","robustness","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_search_sorting_summary.csv", row.names=FALSE)
png("outputs/figures/r_search_sorting_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$search_sorting_quality, data$search_sorting_risk); colnames(m) <- data$case_name; rownames(m) <- c("Search/sorting quality", "Search/sorting risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Search and Sorting Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
