data <- read.csv("data/synthetic_greedy_cases.csv", stringsAsFactors = FALSE)
data$greedy_quality <- 100 * (0.12*data$local_rule_clarity + 0.12*data$global_objective_clarity + 0.12*data$greedy_choice_evidence + 0.10*data$optimal_substructure_evidence + 0.10*data$feasibility_check_quality + 0.10*data$edge_case_coverage + 0.10*data$counterexample_testing + 0.08*data$traceability + 0.08*data$robustness + 0.08*data$governance_readiness)
data$greedy_risk <- 100 * rowMeans(1 - data[, c("local_rule_clarity","global_objective_clarity","greedy_choice_evidence","optimal_substructure_evidence","feasibility_check_quality","edge_case_coverage","counterexample_testing","traceability","robustness","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_greedy_algorithm_summary.csv", row.names=FALSE)
png("outputs/figures/r_greedy_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$greedy_quality, data$greedy_risk); colnames(m) <- data$case_name; rownames(m) <- c("Greedy quality", "Greedy risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Greedy Algorithm Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
