data <- read.csv("data/synthetic_graph_search_cases.csv", stringsAsFactors = FALSE)
data$graph_search_score <- 100 * (0.11*data$graph_definition + 0.11*data$node_edge_clarity + 0.10*data$weight_documentation + 0.10*data$constraint_documentation + 0.10*data$traversal_traceability + 0.09*data$alternative_path_reporting + 0.09*data$failure_handling + 0.08*data$update_freshness + 0.08*data$distributional_review + 0.09*data$governance_review + 0.05*data$communication_clarity)
data$graph_search_risk <- 100 * rowMeans(1 - data[, c("graph_definition","node_edge_clarity","weight_documentation","constraint_documentation","traversal_traceability","alternative_path_reporting","failure_handling","update_freshness","distributional_review","governance_review")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_graph_search_summary.csv", row.names=FALSE)
png("outputs/figures/r_graph_search_score_vs_risk.png", width=1500, height=850)
m <- rbind(data$graph_search_score, data$graph_search_risk)
colnames(m) <- data$case_name
rownames(m) <- c("Graph search score", "Graph search risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Graph Search Score vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
edges <- read.csv("data/synthetic_graph_edges.csv", stringsAsFactors=FALSE)
nodes <- unique(c(edges$source, edges$target))
density <- nrow(edges) / (length(nodes) * (length(nodes)-1))
write.csv(data.frame(node_count=length(nodes), directed_edge_count=nrow(edges), density=density), "outputs/tables/r_graph_density.csv", row.names=FALSE)
print(data)
