args <- commandArgs(trailingOnly = TRUE)
procedural_portability <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
notation_change <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.98)
translation_pathway <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.92)
teaching_value <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.96)
practical_utility <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.96)
institutional_adoption <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.92)
trust_verification <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.90)
historical_significance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.98)
ethical_caution <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.84)
modern_resonance <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.98)

score <- mean(c(procedural_portability, notation_change, translation_pathway, teaching_value, practical_utility, institutional_adoption, trust_verification, historical_significance, ethical_caution, modern_resonance))
cat(sprintf("reception_score=%.6f\n", score))
