data <- read.csv("data/synthetic_approximation_algorithm_cases.csv", stringsAsFactors = FALSE)
data$approximation_quality <- 100 * (0.12*data$objective_clarity + 0.12*data$feasibility_preservation + 0.12*data$guarantee_clarity + 0.10*data$assumption_validity + 0.10*data$bound_evidence + 0.10*data$runtime_practicality + 0.08*data$gap_reporting + 0.08*data$edge_case_coverage + 0.08*data$traceability + 0.10*data$governance_readiness)
data$approximation_risk <- 100 * rowMeans(1 - data[, c("objective_clarity","feasibility_preservation","guarantee_clarity","assumption_validity","bound_evidence","runtime_practicality","gap_reporting","edge_case_coverage","traceability","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_approximation_algorithm_summary.csv", row.names=FALSE)
png("outputs/figures/r_approximation_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$approximation_quality, data$approximation_risk); colnames(m) <- data$case_name; rownames(m) <- c("Approximation quality", "Approximation risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Approximation Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
