args <- commandArgs(trailingOnly = TRUE)
input_drift <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.31)
label_drift <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.16)
performance_decay <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.10)
calibration_gap <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.14)
subgroup_gap <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.15)
override_rate <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.11)
score <- mean(c(input_drift, label_drift, performance_decay, calibration_gap, subgroup_gap, override_rate))
cat(sprintf("decay_risk_score=%.6f\n", score))
