objective_direction(minimize).
objective_direction(maximize).
constraint_type(hard_constraint).
constraint_type(soft_constraint).
constraint_type(penalty_constraint).
constraint_type(fairness_constraint).
constraint_type(safety_constraint).
constraint_type(resource_constraint).
requires_governance(objective_documentation).
requires_governance(constraint_inventory).
requires_governance(feasible_set_review).
requires_governance(tradeoff_analysis).
requires_governance(sensitivity_report).
requires_governance(robustness_review).
requires_governance(fairness_review).
requires_governance(audit_trail).
risk(proxy_objective).
risk(missing_constraint).
risk(hidden_tradeoff).
risk(false_optimality).
risk(unreviewed_uncertainty).
risk(unequal_impact).
