args <- commandArgs(trailingOnly = TRUE)
feedback_centrality <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
control_relevance <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.96)
communication_relevance <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.94)
prediction_relevance <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.86)
stability_relevance <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.96)
amplification_risk <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.90)
automation_ethics <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.92)
ai_relevance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.96)
institutional_relevance <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.92)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.96)

score <- mean(c(feedback_centrality, control_relevance, communication_relevance, prediction_relevance, stability_relevance, amplification_risk, automation_ethics, ai_relevance, institutional_relevance, governance_caution))
cat(sprintf("cybernetic_score=%.6f\n", score))
