args <- commandArgs(trailingOnly = TRUE)
representation_centrality <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.96)
operation_clarity <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.92)
memory_awareness <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.98)
time_analysis <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.88)
space_analysis <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.96)
scale_sensitivity <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.90)
abstraction_maturity <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.82)
systems_relevance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.96)
historical_influence <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.98)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.86)

score <- mean(c(representation_centrality, operation_clarity, memory_awareness, time_analysis, space_analysis, scale_sensitivity, abstraction_maturity, systems_relevance, historical_influence, governance_caution))
cat(sprintf("history_score=%.6f\n", score))
