data <- read.csv("data/synthetic_tractability_cases.csv", stringsAsFactors = FALSE)
data$tractability_quality <- 100 * (0.10*data$input_definition_clarity + 0.12*data$complexity_evidence + 0.10*data$structure_exploitation + 0.10*data$exact_method_feasibility + 0.10*data$approximation_readiness + 0.10*data$heuristic_validation + 0.12*data$benchmark_evidence + 0.08*data$timeout_handling + 0.10*data$governance_readiness + 0.08*data$communication_clarity)
data$tractability_risk <- 100 * rowMeans(1 - data[, c("input_definition_clarity","complexity_evidence","structure_exploitation","exact_method_feasibility","approximation_readiness","heuristic_validation","benchmark_evidence","timeout_handling","governance_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_tractability_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_tractability_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$tractability_quality, data$tractability_risk); colnames(m) <- data$case_name; rownames(m) <- c("Tractability quality", "Tractability risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Tractability Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
