args <- commandArgs(trailingOnly = TRUE)
structured_control <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
correctness <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.94)
invariants <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.90)
proof_relevance <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.92)
formal_methods <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.88)
readability <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.98)
maintainability <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.96)
algorithmic_relevance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.90)
system_design <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.88)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.92)

score <- mean(c(structured_control, correctness, invariants, proof_relevance, formal_methods, readability, maintainability, algorithmic_relevance, system_design, governance_caution))
cat(sprintf("discipline_score=%.6f\n", score))
