args <- commandArgs(trailingOnly = TRUE)
selected <- ifelse(length(args) >= 1, as.numeric(args[1]), 420)
n <- ifelse(length(args) >= 2, as.numeric(args[2]), 1000)
tp <- ifelse(length(args) >= 3, as.numeric(args[3]), 260)
fp <- ifelse(length(args) >= 4, as.numeric(args[4]), 160)
fn <- ifelse(length(args) >= 5, as.numeric(args[5]), 140)
tn <- ifelse(length(args) >= 6, as.numeric(args[6]), 440)
mean_score <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.62)
observed_rate <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.58)
measurement_validity <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.72)
contestability <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.66)
remediation <- ifelse(length(args) >= 11, as.numeric(args[11]), 0.60)
selection_rate <- selected / n
false_positive_rate <- fp / (fp + tn)
false_negative_rate <- fn / (tp + fn)
true_positive_rate <- tp / (tp + fn)
calibration_gap <- abs(mean_score - observed_rate)
fairness_evidence <- 1 - mean(c(false_positive_rate, false_negative_rate, calibration_gap))
justice_capacity <- mean(c(fairness_evidence, measurement_validity, contestability, remediation))
cat(sprintf("selection_rate=%.6f\n", selection_rate))
cat(sprintf("false_positive_rate=%.6f\n", false_positive_rate))
cat(sprintf("false_negative_rate=%.6f\n", false_negative_rate))
cat(sprintf("true_positive_rate=%.6f\n", true_positive_rate))
cat(sprintf("calibration_gap=%.6f\n", calibration_gap))
cat(sprintf("justice_capacity_score=%.6f\n", justice_capacity))
