args <- commandArgs(trailingOnly = TRUE)
error_likelihood <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.34)
severity <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.92)
exposure <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.78)
contestability <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.42)
ownership <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.48)
monitoring <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.45)
appeals <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.40)
repair <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.35)
governance <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.50)
harm_risk <- error_likelihood * severity * exposure * (1 - contestability)
responsibility_capacity <- mean(c(ownership, monitoring, appeals, repair, governance))
remediation_gap <- max(0, severity - repair)
cat(sprintf("harm_risk_score=%.6f\n", harm_risk))
cat(sprintf("responsibility_capacity=%.6f\n", responsibility_capacity))
cat(sprintf("remediation_gap=%.6f\n", remediation_gap))
