constraint_type(hard_constraint).
constraint_type(soft_constraint).
constraint_type(equality).
constraint_type(inequality).
constraint_type(compatibility).
feasibility_status(feasible).
feasibility_status(infeasible).
feasibility_status(unsatisfiable).
requires_governance(variable_inventory).
requires_governance(domain_record).
requires_governance(constraint_inventory).
requires_governance(violation_report).
requires_governance(pruning_log).
requires_governance(exception_handling).
requires_governance(appeal_pathway).
risk(missing_variable).
risk(incomplete_domain).
risk(hidden_constraint).
risk(over_rigid_rule).
risk(conflicting_constraints).
risk(false_feasibility).
