args <- commandArgs(trailingOnly = TRUE)
arithmetic_method <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
algebraic_procedure <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.76)
representation <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.98)
transformation <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.88)
proof_relation <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.78)
transmission <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.98)
etymology <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.98)
institutional_adoption <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.94)
historiographic_caution <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.92)
modern_resonance <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.98)

score <- mean(c(arithmetic_method, algebraic_procedure, representation, transformation, proof_relation, transmission, etymology, institutional_adoption, historiographic_caution, modern_resonance))
cat(sprintf("method_score=%.6f\n", score))
