args <- commandArgs(trailingOnly = TRUE)
stakes <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.94)
notice <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.70)
reasons <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.62)
evidence_access <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.48)
human_review <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.55)
correction <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.52)
remedy <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.44)
contestability <- mean(c(notice, reasons, evidence_access, human_review, correction, remedy))
procedural_risk <- stakes * (1 - contestability)
cat(sprintf("contestability_score=%.6f\n", contestability))
cat(sprintf("procedural_risk=%.6f\n", procedural_risk))
