.PHONY: run-python run-r run-calculators

run-python:
	python3 python/algorithms_in_scientific_computing_audit.py

run-r:
	Rscript r/algorithms_in_scientific_computing_summary.R

run-calculators:
	bash calculators/run_calculator_smoke_tests.sh
