args <- commandArgs(trailingOnly = TRUE)
programming_structure <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
symbolic_generality <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.86)
machine_orientation <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.98)
mathematical_grounding <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.94)
imaginative_reach <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.86)
limit_awareness <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.76)
collaboration <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.92)
authorship <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.90)
modern_resonance <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.98)
ai_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.82)

score <- mean(c(programming_structure, symbolic_generality, machine_orientation, mathematical_grounding, imaginative_reach, limit_awareness, collaboration, authorship, modern_resonance, ai_caution))
cat(sprintf("imagination_score=%.6f\n", score))
