args <- commandArgs(trailingOnly = TRUE)
severity <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.92)
likelihood <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.44)
detectability <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.42)
ownership <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.60)
documentation <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.62)
monitoring <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.58)
contestability <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.52)
remediation <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.46)
stop_authority <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.50)
control_effectiveness <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.48)
inherent_risk <- severity * likelihood * (1 - detectability)
governance_readiness <- mean(c(ownership, documentation, monitoring, contestability, remediation, stop_authority))
residual_risk <- inherent_risk * (1 - control_effectiveness)
cat(sprintf("inherent_risk_score=%.6f\n", inherent_risk))
cat(sprintf("governance_readiness_score=%.6f\n", governance_readiness))
cat(sprintf("residual_risk_score=%.6f\n", residual_risk))
