data <- read.csv("data/synthetic_software_architecture_cases.csv", stringsAsFactors = FALSE)
data$architecture_quality <- 100 * (0.12*data$boundary_clarity + 0.12*data$modular_cohesion + 0.12*data$dependency_control + 0.10*data$interface_discipline + 0.10*data$state_ownership + 0.10*data$failure_containment + 0.08*data$scalability_readiness + 0.10*data$security_boundaries + 0.08*data$observability + 0.08*data$governance_readiness)
data$architecture_risk <- 100 * rowMeans(1 - data[, c("boundary_clarity","modular_cohesion","dependency_control","interface_discipline","state_ownership","failure_containment","security_boundaries","observability")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_software_architecture_summary.csv", row.names=FALSE)
png("outputs/figures/r_architecture_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$architecture_quality, data$architecture_risk); colnames(m) <- data$case_name; rownames(m) <- c("Architecture quality", "Architecture risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Architecture Quality vs. Architecture Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
