args <- commandArgs(trailingOnly = TRUE)
faithfulness <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.70)
stability <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.74)
understandability <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.62)
actionability <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.58)
uncertainty <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.46)
documentation <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.68)
contestability <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.55)
governance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.60)
stakes <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.88)
explanation_quality <- mean(c(faithfulness, stability, understandability, actionability, uncertainty))
transparency_capacity <- mean(c(documentation, governance, uncertainty))
accountability_capacity <- mean(c(explanation_quality, transparency_capacity, contestability, governance))
explanation_risk <- stakes * (1 - accountability_capacity)
cat(sprintf("explanation_quality_score=%.6f\n", explanation_quality))
cat(sprintf("transparency_capacity_score=%.6f\n", transparency_capacity))
cat(sprintf("accountability_capacity_score=%.6f\n", accountability_capacity))
cat(sprintf("explanation_risk_score=%.6f\n", explanation_risk))
