data <- read.csv("data/synthetic_search_strategy_cases.csv", stringsAsFactors = FALSE)
data$search_strategy_quality <- 100 * (0.12*data$search_space_clarity + 0.12*data$candidate_generation_completeness + 0.10*data$constraint_quality + 0.10*data$pruning_soundness + 0.10*data$bound_validity + 0.10*data$objective_clarity + 0.10*data$edge_case_coverage + 0.08*data$traceability + 0.10*data$complexity_awareness + 0.08*data$governance_readiness)
data$search_strategy_risk <- 100 * rowMeans(1 - data[, c("search_space_clarity","candidate_generation_completeness","constraint_quality","pruning_soundness","bound_validity","objective_clarity","edge_case_coverage","traceability","complexity_awareness","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_search_strategy_summary.csv", row.names=FALSE)
png("outputs/figures/r_search_strategy_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$search_strategy_quality, data$search_strategy_risk); colnames(m) <- data$case_name; rownames(m) <- c("Search strategy quality", "Search strategy risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Search Strategy Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
