data <- read.csv("data/synthetic_complexity_scalability_cases.csv", stringsAsFactors = FALSE)
data$scalability_quality <- 100 * (0.12*data$input_definition_clarity + 0.12*data$time_complexity_clarity + 0.10*data$space_complexity_clarity + 0.12*data$benchmark_evidence + 0.10*data$bottleneck_identification + 0.10*data$threshold_reporting + 0.08*data$degradation_planning + 0.08*data$monitoring_readiness + 0.10*data$governance_readiness + 0.08*data$equity_under_scale_review)
data$scalability_risk <- 100 * rowMeans(1 - data[, c("input_definition_clarity","time_complexity_clarity","space_complexity_clarity","benchmark_evidence","bottleneck_identification","threshold_reporting","degradation_planning","monitoring_readiness","governance_readiness","equity_under_scale_review")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_complexity_scalability_summary.csv", row.names=FALSE)
png("outputs/figures/r_scalability_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$scalability_quality, data$scalability_risk); colnames(m) <- data$case_name; rownames(m) <- c("Scalability quality", "Scalability risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Scalability Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
