args <- commandArgs(trailingOnly = TRUE)
high_level_language <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
scientific_expression <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.98)
compiler_optimization <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.94)
numerical_relevance <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.96)
portability <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.90)
performance_credibility <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.96)
language_history <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.94)
formal_specification <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.84)
maintainability <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.90)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.88)

score <- mean(c(high_level_language, scientific_expression, compiler_optimization, numerical_relevance, portability, performance_credibility, language_history, formal_specification, maintainability, governance_caution))
cat(sprintf("birth_score=%.6f\n", score))
