data <- read.csv("data/synthetic_reliability_cases.csv", stringsAsFactors = FALSE)
data$reliability_quality <- 100 * (0.12*data$specification_clarity + 0.10*data$test_coverage_rationale + 0.12*data$oracle_quality + 0.10*data$edge_case_testing + 0.10*data$regression_discipline + 0.10*data$property_checks + 0.10*data$reproducibility_evidence + 0.10*data$observability + 0.08*data$security_testing + 0.08*data$governance_readiness)
data$reliability_risk <- 100 * rowMeans(1 - data[, c("specification_clarity","test_coverage_rationale","oracle_quality","edge_case_testing","regression_discipline","property_checks","reproducibility_evidence","observability","security_testing")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_testing_verification_reliability_summary.csv", row.names=FALSE)
png("outputs/figures/r_reliability_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$reliability_quality, data$reliability_risk); colnames(m) <- data$case_name; rownames(m) <- c("Reliability quality", "Reliability risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Reliability Quality vs. Reliability Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
