data <- read.csv("data/synthetic_control_flow_cases.csv", stringsAsFactors = FALSE)
data$control_flow_quality <- 100 * (0.12*data$path_clarity + 0.10*data$loop_structure + 0.10*data$recursion_structure + 0.10*data$state_update_discipline + 0.12*data$termination_evidence + 0.12*data$invariant_evidence + 0.10*data$edge_case_coverage + 0.08*data$error_handling + 0.08*data$traceability + 0.08*data$governance_readiness)
data$control_flow_risk <- 100 * rowMeans(1 - data[, c("path_clarity","loop_structure","state_update_discipline","termination_evidence","invariant_evidence","edge_case_coverage","error_handling","traceability","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_control_flow_summary.csv", row.names=FALSE)
png("outputs/figures/r_control_flow_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$control_flow_quality, data$control_flow_risk); colnames(m) <- data$case_name; rownames(m) <- c("Control-flow quality", "Control-flow risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Control-Flow Quality vs. Control-Flow Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
