data <- read.csv("data/synthetic_ranking_signal_cases.csv", stringsAsFactors = FALSE)
data$ranking_quality_score <- 100 * (0.10*data$lexical_evidence + 0.09*data$field_weighting + 0.09*data$metadata_quality + 0.08*data$freshness_logic + 0.08*data$authority_evidence + 0.09*data$semantic_similarity + 0.10*data$evaluation_discipline + 0.08*data$diversity_handling + 0.07*data$feedback_governance + 0.08*data$provenance_support + 0.08*data$explainability + 0.06*data$communication_clarity)
data$ranking_risk <- 100 * rowMeans(1 - data[, c("lexical_evidence","metadata_quality","freshness_logic","authority_evidence","evaluation_discipline","feedback_governance","provenance_support","explainability","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_ranking_signal_summary.csv", row.names=FALSE)
png("outputs/figures/r_ranking_quality_vs_risk.png", width=1500, height=850)
m <- rbind(data$ranking_quality_score, data$ranking_risk)
colnames(m) <- data$case_name
rownames(m) <- c("Ranking quality", "Ranking risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Ranking Quality vs. Ranking Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
