args <- commandArgs(trailingOnly = TRUE)
evidence_grounding <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.96)
scope_clarity <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.98)
anachronism_control <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.96)
network_awareness <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.88)
etymology_caution <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.98)
transmission_depth <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.90)
credit_distribution <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.90)
public_usefulness <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.96)
historical_significance <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.98)
modern_resonance <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.98)

score <- mean(c(evidence_grounding, scope_clarity, anachronism_control, network_awareness, etymology_caution, transmission_depth, credit_distribution, public_usefulness, historical_significance, modern_resonance))
cat(sprintf("origin_care_score=%.6f\n", score))
