args <- commandArgs(trailingOnly = TRUE)
stored_program <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
memory_organization <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.96)
control_structure <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.94)
program_as_data <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.98)
implementation_influence <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.96)
bottleneck_awareness <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.82)
collaboration_context <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.86)
software_relevance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.98)
ai_infrastructure <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.90)
governance_caution <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.88)

score <- mean(c(stored_program, memory_organization, control_structure, program_as_data, implementation_influence, bottleneck_awareness, collaboration_context, software_relevance, ai_infrastructure, governance_caution))
cat(sprintf("architecture_score=%.6f\n", score))
