data <- read.csv("data/synthetic_big_o_claims.csv", stringsAsFactors = FALSE)
data$big_o_claim_quality <- 100 * (0.12*data$input_definition_clarity + 0.10*data$resource_scope_clarity + 0.10*data$case_assumption_clarity + 0.12*data$derivation_quality + 0.10*data$tightness_clarity + 0.12*data$benchmark_support + 0.10*data$threshold_reporting + 0.08*data$hidden_cost_review + 0.08*data$governance_readiness + 0.08*data$communication_clarity)
data$big_o_claim_risk <- 100 * rowMeans(1 - data[, c("input_definition_clarity","resource_scope_clarity","case_assumption_clarity","derivation_quality","tightness_clarity","benchmark_support","threshold_reporting","hidden_cost_review","governance_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_big_o_claim_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_big_o_claim_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$big_o_claim_quality, data$big_o_claim_risk); colnames(m) <- data$claim_name; rownames(m) <- c("Big-O claim quality", "Big-O claim risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Big-O Claim Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
