args <- commandArgs(trailingOnly = TRUE)
time <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.56)
information <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.62)
authority <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.58)
training <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.60)
protection <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.48)
accepted <- ifelse(length(args) >= 6, as.numeric(args[6]), 920)
total <- ifelse(length(args) >= 7, as.numeric(args[7]), 1000)
overrides <- ifelse(length(args) >= 8, as.numeric(args[8]), 18)
reviewed <- ifelse(length(args) >= 9, as.numeric(args[9]), 1000)
escalation <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.54)
contestability <- ifelse(length(args) >= 11, as.numeric(args[11]), 0.52)
governance <- ifelse(length(args) >= 12, as.numeric(args[12]), 0.60)
stakes <- ifelse(length(args) >= 13, as.numeric(args[13]), 0.88)
review_capacity <- mean(c(time, information, authority, training, protection))
reliance <- ifelse(total == 0, 0, accepted / total)
override_rate <- ifelse(reviewed == 0, 0, overrides / reviewed)
judgment_capacity <- mean(c(review_capacity, escalation, contestability, governance))
review_risk <- stakes * (1 - judgment_capacity)
cat(sprintf("review_capacity_score=%.6f\n", review_capacity))
cat(sprintf("reliance_score=%.6f\n", reliance))
cat(sprintf("override_rate=%.6f\n", override_rate))
cat(sprintf("judgment_capacity_score=%.6f\n", judgment_capacity))
cat(sprintf("review_risk_score=%.6f\n", review_risk))
