data <- read.csv("data/synthetic_space_complexity_cases.csv", stringsAsFactors = FALSE)
data$space_claim_quality <- 100 * (0.09*data$input_space_clarity + 0.11*data$auxiliary_space_clarity + 0.08*data$output_space_clarity + 0.12*data$peak_memory_evidence + 0.11*data$data_structure_fit + 0.10*data$time_space_tradeoff_clarity + 0.10*data$io_and_data_movement_awareness + 0.09*data$streaming_or_external_memory_readiness + 0.08*data$failure_handling + 0.07*data$governance_readiness + 0.05*data$communication_clarity)
data$space_claim_risk <- 100 * rowMeans(1 - data[, c("input_space_clarity","auxiliary_space_clarity","output_space_clarity","peak_memory_evidence","data_structure_fit","time_space_tradeoff_clarity","io_and_data_movement_awareness","streaming_or_external_memory_readiness","failure_handling","governance_readiness","communication_clarity")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_space_complexity_audit_summary.csv", row.names=FALSE)
png("outputs/figures/r_space_claim_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$space_claim_quality, data$space_claim_risk); colnames(m) <- data$case_name; rownames(m) <- c("Space claim quality", "Space claim risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Space Complexity Claim Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
