args <- commandArgs(trailingOnly = TRUE)
target_legitimacy <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.42)
data_legitimacy <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.48)
contestability <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.40)
human_judgment <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.46)
governance_capacity <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.44)
repairability <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.38)
stakes <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.94)
irreversibility <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.78)
proxy_illegitimacy <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.70)
readiness <- mean(c(target_legitimacy, data_legitimacy, contestability, human_judgment, governance_capacity, repairability))
pressure <- mean(c(stakes, irreversibility, 1 - governance_capacity, proxy_illegitimacy))
decision <- ifelse(pressure >= 0.70 && readiness < 0.65, "refuse", ifelse(readiness < 0.65, "review_or_human_led", "allow_with_controls"))
cat(sprintf("responsible_use_readiness_score=%.6f\n", readiness))
cat(sprintf("non_use_pressure_score=%.6f\n", pressure))
cat(sprintf("non_use_decision=%s\n", decision))
