args <- commandArgs(trailingOnly = TRUE)
unknown_representation <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.98)
procedural_transformation <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.94)
abstraction <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.96)
proof_relation <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.88)
translation_continuity <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.90)
practical_grounding <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.92)
philosophical_depth <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.96)
historical_significance <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.98)
ethical_caution <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.86)
modern_resonance <- ifelse(length(args) >= 10, as.numeric(args[10]), 0.98)

score <- mean(c(unknown_representation, procedural_transformation, abstraction, proof_relation, translation_continuity, practical_grounding, philosophical_depth, historical_significance, ethical_caution, modern_resonance))
cat(sprintf("unknown_variable_score=%.6f\n", score))
