args <- commandArgs(trailingOnly = TRUE)
acceptance <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.93)
quality <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.71)
overreliance_gap <- max(0, acceptance - quality)
calibration_error <- abs(acceptance - quality)
cat(sprintf("acceptance_rate=%.6f\n", acceptance))
cat(sprintf("model_quality=%.6f\n", quality))
cat(sprintf("overreliance_gap=%.6f\n", overreliance_gap))
cat(sprintf("trust_calibration_error=%.6f\n", calibration_error))
