args <- commandArgs(trailingOnly = TRUE)
evidence <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.62)
validation <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.58)
reversibility <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.46)
contestability <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.52)
governance <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.60)
human_review <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.58)
automated <- ifelse(length(args) >= 7, as.numeric(args[7]), 760)
total <- ifelse(length(args) >= 8, as.numeric(args[8]), 1000)
stakes <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.92)
readiness <- mean(c(evidence, validation, reversibility, contestability, governance, human_review))
reliance <- ifelse(total == 0, 0, automated / total)
risk <- stakes * (1 - readiness)
cat(sprintf("delegation_readiness_score=%.6f\n", readiness))
cat(sprintf("automation_reliance_score=%.6f\n", reliance))
cat(sprintf("delegation_risk_score=%.6f\n", risk))
