args <- commandArgs(trailingOnly = TRUE)
data_share <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.28)
deployment_share <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.36)
label_positive_rate <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.33)
verified_positive_rate <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.43)
provenance_risk <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.66)
measurement_weakness <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.58)
proxy_risk <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.62)
remediation <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.42)
representation_gap <- abs(data_share - deployment_share)
label_gap <- abs(label_positive_rate - verified_positive_rate)
historical_risk <- mean(c(provenance_risk, measurement_weakness, proxy_risk, 1 - remediation))
cat(sprintf("representation_gap=%.6f\n", representation_gap))
cat(sprintf("label_gap=%.6f\n", label_gap))
cat(sprintf("historical_risk_score=%.6f\n", historical_risk))
