args <- commandArgs(trailingOnly = TRUE)
likelihood <- ifelse(length(args) >= 1, as.numeric(args[1]), 0.42)
severity <- ifelse(length(args) >= 2, as.numeric(args[2]), 0.86)
detectability <- ifelse(length(args) >= 3, as.numeric(args[3]), 0.38)
controllability <- ifelse(length(args) >= 4, as.numeric(args[4]), 0.44)
monitoring <- ifelse(length(args) >= 5, as.numeric(args[5]), 0.42)
fallback <- ifelse(length(args) >= 6, as.numeric(args[6]), 0.36)
rollback <- ifelse(length(args) >= 7, as.numeric(args[7]), 0.50)
escalation <- ifelse(length(args) >= 8, as.numeric(args[8]), 0.46)
repair <- ifelse(length(args) >= 9, as.numeric(args[9]), 0.40)
failure_risk <- likelihood * severity * (1 - detectability) * (1 - controllability)
priority <- likelihood * severity * (1 - detectability)
resilience <- mean(c(monitoring, fallback, rollback, escalation, repair))
cat(sprintf("failure_risk_score=%.6f\n", failure_risk))
cat(sprintf("priority_score=%.6f\n", priority))
cat(sprintf("resilience_capacity=%.6f\n", resilience))
