data <- read.csv("data/synthetic_heuristic_cases.csv", stringsAsFactors = FALSE)
data$heuristic_quality <- 100 * (0.12*data$purpose_clarity + 0.12*data$rule_transparency + 0.12*data$benchmark_evidence + 0.10*data$parameter_documentation + 0.10*data$robustness_testing + 0.10*data$edge_case_coverage + 0.08*data$fairness_review + 0.08*data$traceability + 0.08*data$monitoring_readiness + 0.10*data$governance_readiness)
data$heuristic_risk <- 100 * rowMeans(1 - data[, c("purpose_clarity","rule_transparency","benchmark_evidence","parameter_documentation","robustness_testing","edge_case_coverage","fairness_review","traceability","monitoring_readiness","governance_readiness")])
dir.create("outputs/tables", recursive=TRUE, showWarnings=FALSE)
dir.create("outputs/figures", recursive=TRUE, showWarnings=FALSE)
write.csv(data, "outputs/tables/r_heuristic_design_summary.csv", row.names=FALSE)
png("outputs/figures/r_heuristic_quality_vs_risk.png", width=1400, height=800)
m <- rbind(data$heuristic_quality, data$heuristic_risk); colnames(m) <- data$case_name; rownames(m) <- c("Heuristic quality", "Heuristic risk")
barplot(m, beside=TRUE, las=2, ylim=c(0,100), ylab="Score", main="Heuristic Quality vs. Risk")
legend("topleft", legend=rownames(m), pch=15, bty="n"); grid(); dev.off()
print(data)
